# -*- coding: utf-8 -*-
"""Text_Summarizer_Using_BART_Transformer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m_Q9BN-cSY718xt2G9AF9yeNM-qAmeqR

# Text Summarization using BART Transformer

BART (Bidirectional and Auto-Regressive Transformers) is a sequence-to-sequence model developed by Meta that combines a bidirectional encoder (like BERT) with an autoregressive decoder (like GPT)

### Loading the dataset
"""

!pip install datasets

from datasets import load_dataset

ds = load_dataset("knkarthick/dialogsum")

ds

ds['train'][1]

ds['train'][1]['dialogue']

ds['train'][1]['summary']  #abstractive summarization (words aren't directly extracted form the text, instead takes the keywords, preprocess it and generate a new summary)

"""# 1. Without Fine-Tuning"""

!pip install transformers

# Load model directly
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

tokenizer = AutoTokenizer.from_pretrained("facebook/bart-large-cnn")
model = AutoModelForSeq2SeqLM.from_pretrained("facebook/bart-large-cnn")

article_1 = ds['train'][1]['dialogue']

inputs = tokenizer(article_1, max_length=1024, return_tensors="pt")

#generate summary
summary_ids = model.generate(inputs["input_ids"], num_beams=2, min_length=10, max_length=20)

tokenizer.decode(summary_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)

ds['train'][1]['summary']

"""# 2. With Fine - Tuning

'input_ids' represent the tokenized form of your input text. Each token (which could be a word or part of a word) is converted into a unique integer ID based on the model's vocabulary.

'attention_mask' is a tensor that indicates which tokens should be attended to and which should be ignored (usually padding tokens). It’s a binary mask where typically:

- 1 indicates that the token should be attended to.
- 0 indicates that the token is padding and should be ignored.

In sequence-to-sequence models, such as text summarization models, you have:

- Input IDs: Tokenized IDs of the source text (e.g., dialogue).
- Target IDs: Tokenized IDs of the target text (e.g., summary).<br>

During training, the model computes the loss between the predicted sequence and the target sequence. To ensure that padding tokens do not affect this loss calculation, padding token IDs are often replaced with -100.


"""

#tokenization
def preprocess_function(batch):
  source = batch['dialogue']
  target = batch['summary']
  source_ids = tokenizer(source, truncation=True, padding="max_length", max_length=128)    #padding - to make the data equal in size
  target_ids = tokenizer(target, truncation=True, padding="max_length", max_length=128)

  # Replace pad token id with -100 for labels to ignore padding in loss computation
  labels = target_ids["input_ids"]
  labels = [[label if label != tokenizer.pad_token else -100 for label in labels_example] for labels_example in labels]

  return {
      "input_ids": source_ids["input_ids"],
      "attention_mask": source_ids["attention_mask"],   #attention mask - to specify which token should be attended (0 and 1)
      "labels": labels
  }

df_source = ds.map(preprocess_function, batched=True)

from transformers import TrainingArguments, Trainer

#define training arguments
training_args = TrainingArguments(
    output_dir="./results",
    per_device_train_batch_size=8,
    num_train_epochs=2,
    remove_unused_columns=True
)

#create trainer object
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=df_source["train"],
    eval_dataset=df_source["test"]
)

trainer.train()

# evaluate the model
eval_results = trainer.evaluate()

print(eval_results)

"""# Saving the model"""

# save the model and tokenizer after training
model.save_pretrained("./results/bart_finetuned_model")
tokenizer.save_pretrained("./results/bart_finetuned_model")

"""# Summarizing the custom data using saved model and tokenizer"""

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# load the trained model
model = AutoModelForSeq2SeqLM.from_pretrained("./results/bart_finetuned_model")
tokenizer = AutoTokenizer.from_pretrained("./results/bart_finetuned_model")

# Function to summarize a blog post
def summarize(blog_post):
    # Tokenize the input blog post
    inputs = tokenizer(blog_post, max_length=1024, truncation=True, return_tensors="pt")

    # Generate the summary
    summary_ids = model.generate(inputs["input_ids"], max_length=150, min_length=40, length_penalty=2.0, num_beams=4, early_stopping=True)

    # Decode the summary
    summary = tokenizer.decode(summary_ids[0], skip_special_tokens=True)
    return summary

# Example blog post
blog_post = """
As Yogi Berra famously said, it’s tough to make predictions, especially about the future. But had the baseball legend spent any time observing the UN climate negotiations, he could have safely predicted that climate finance will prove to be a key sticking point at COP29 in Baku at the end of this year.

‘Who will pay and how much?’ are perennial questions at the climate talks, but this year, the discussions about climate finance will be especially prominent. At COP29, Parties to the Paris Agreement must negotiate a new climate finance goal, to replace the existing commitment from 2009 for developed countries to provide US$100 billion climate finance annually from 2020 to 2025 - a commitment that only in 2022 was starting to be fulfilled, according to a recent OECD report.

It is vital that the forthcoming Bonn Climate Change Conference sends the right political signals, and lays the procedural and technical groundwork for an ambitious climate finance deal in Baku.

A pressing need

With global warming already destabilising the climate and devastating people’s lives and livelihoods, the need for finance to reduce greenhouse gas emissions and to adapt to a warming world has never been more pressing.

The sums involved are large. The Paris Agreement’s Global Stocktake process estimates that US$5.8-5.9 trillion is required to implement Nationally Determined Contributions (NDCs) in developing countries up to 2030. They will require US$215-387 billion annually over this period for adaptation. Investments of US$1.5 trillion in renewable energy are required worldwide every year up until 2030, according to IRENA.

But these sums are also affordable and beneficial for developed countries. They should be seen in the context of ongoing investments in energy and other infrastructure: around US$2.3 trillion was invested in energy infrastructure in 2023, of which US$1.74 trillion was in clean energy. These investments will generate strong returns for their investors and reduce the costs for energy consumers.

And, crucially, they should also be seen in the context of the alternative. The latest research estimates that the world economy is already set to face a 19% income reduction within the next 26 years based on the levels of warming we have already locked in. The more we delay and the more the planet heats, the greater the economic costs will be.

Laying the foundations for a new finance goal

While financial resources are beginning to flow, they are not flowing fast enough, and certainly not flowing to those developing countries where need is greatest and access to finance is most challenging.

The UN climate framework provides mechanisms that can enable those flows of climate finance. Back in 2015, parties at the climate talks agreed to establish a “new collective quantified goal” (NCQG) for climate finance. They agreed that the NCQG would be set prior to 2025.

The  ultimate size of the NCQG will be a product of the negotiations, but Parties have agreed it must be a significant increase from the floor of US$100 billion annually. For WWF, it must be needs-based and sufficiently ambitious to meet the scale of the challenge we face, and immediately accessible to help countries that are already facing the chaos of a destabilised climate system.

While developed countries are expected to provide financial and technical support, developing countries also have a role to play. Parties are due to submit revised NDCs in 2025, presenting how they plan to reduce emissions and adapt to climate change. Developing countries have the opportunity to use their NDCs to set out how international climate finance can support them and increase their ambition. To do this, they need to know the finance will be forthcoming.
"""

# Get the summary
summary = summarize(blog_post)
print("Summary:", summary)

